package eu.europeana.direct.helpers;

import java.util.HashMap;
import java.util.Map;

public class LanguageCodes {

	private Map<String, String> languages = new HashMap<>();
	
	public LanguageCodes(){
		
		languages.put("aar", "aa");
		languages.put("abk", "ab");
		languages.put("afr", "af");
		languages.put("aka", "ak");
		languages.put("alb", "sq");
		languages.put("amh", "am");
		languages.put("ara", "ar");
		languages.put("arg", "an");
		languages.put("arm", "hy");
		languages.put("asm", "as");
		languages.put("ava", "av");
		languages.put("ave", "ae");
		languages.put("aym", "ay");
		languages.put("aze", "az");
		languages.put("bak", "ba");
		languages.put("bam", "bm");
		languages.put("baq", "eu");
		languages.put("bel", "be");
		languages.put("ben", "bn");
		languages.put("bih", "bh");
		languages.put("bis", "bi");
		languages.put("bos", "bs");
		languages.put("bre", "br");
		languages.put("bul", "bg");
		languages.put("bur", "my");
		languages.put("cat", "ca");
		languages.put("cha", "ch");
		languages.put("che", "ce");
		languages.put("chi", "zh");
		languages.put("chu", "cu");
		languages.put("chv", "cv");
		languages.put("cor", "kw");
		languages.put("cos", "co");
		languages.put("cre", "cr");
		languages.put("cze", "cs");
		languages.put("dan", "da");
		languages.put("div", "dv");
		languages.put("dut", "nl");
		languages.put("dzo", "dz");
		languages.put("eng", "en");
		languages.put("epo", "eo");
		languages.put("est", "et");
		languages.put("ewe", "ee");
		languages.put("fao", "fo");
		languages.put("fij", "fj");
		languages.put("fin", "fi");
		languages.put("fre", "fr");
		languages.put("fry", "fy");
		languages.put("ful", "ff");
		languages.put("geo", "ka");
		languages.put("ger", "de");
		languages.put("gla", "gd");
		languages.put("gle", "ga");
		languages.put("glg", "gl");
		languages.put("glv", "gv");
		languages.put("gre", "el");
		languages.put("grn", "gn");
		languages.put("guj", "gu");
		languages.put("hat", "ht");
		languages.put("hau", "ha");
		languages.put("heb", "he");
		languages.put("her", "hz");
		languages.put("hin", "hi");
		languages.put("hmo", "ho");
		languages.put("hrv", "hr");
		languages.put("hun", "hu");
		languages.put("ibo", "ig");
		languages.put("ice", "is");
		languages.put("ido", "io");
		languages.put("iii", "ii");
		languages.put("iku", "iu");
		languages.put("ile", "ie");
		languages.put("ina", "ia");
		languages.put("ind", "id");
		languages.put("ipk", "ik");
		languages.put("ita", "it");
		languages.put("jav", "jv");
		languages.put("jpn", "ja");
		languages.put("kal", "kl");
		languages.put("kan", "kn");
		languages.put("kas", "ks");
		languages.put("kau", "kr");
		languages.put("kaz", "kk");
		languages.put("khm", "km");
		languages.put("kik", "ki");
		languages.put("kin", "rw");
		languages.put("kir", "ky");
		languages.put("kom", "kv");
		languages.put("kon", "kg");
		languages.put("kor", "ko");
		languages.put("kua", "kj");
		languages.put("kur", "ku");
		languages.put("lao", "lo");
		languages.put("lat", "la");
		languages.put("lav", "lv");
		languages.put("lim", "li");
		languages.put("lin", "ln");
		languages.put("lit", "lt");
		languages.put("ltz", "lb");
		languages.put("lub", "lu");
		languages.put("lug", "lg");
		languages.put("mac", "mk");
		languages.put("mah", "mh");
		languages.put("mal", "ml");
		languages.put("mao", "mi");
		languages.put("mar", "mr");
		languages.put("may", "ms");
		languages.put("mlg", "mg");
		languages.put("mlt", "mt");
		languages.put("mon", "mn");
		languages.put("nau", "na");
		languages.put("nav", "nv");
		languages.put("nbl", "nr");
		languages.put("nde", "nd");
		languages.put("ndo", "ng");
		languages.put("nep", "ne");
		languages.put("nno", "nn");
		languages.put("nob", "nb");
		languages.put("nor", "no");
		languages.put("nya", "ny");
		languages.put("oci", "oc");
		languages.put("oji", "oj");
		languages.put("ori", "or");
		languages.put("orm", "om");
		languages.put("oss", "os");
		languages.put("pan", "pa");
		languages.put("per", "fa");
		languages.put("pli", "pi");
		languages.put("pol", "pl");
		languages.put("por", "pt");
		languages.put("pus", "ps");
		languages.put("que", "qu");
		languages.put("roh", "rm");
		languages.put("rum", "ro");
		languages.put("run", "rn");
		languages.put("rus", "ru");
		languages.put("sag", "sg");
		languages.put("san", "sa");
		languages.put("sin", "si");
		languages.put("slo", "sk");
		languages.put("slv", "sl");
		languages.put("sme", "se");
		languages.put("smo", "sm");
		languages.put("sna", "sn");
		languages.put("snd", "sd");
		languages.put("som", "so");
		languages.put("sot", "st");
		languages.put("spa", "es");
		languages.put("srd", "sc");
		languages.put("srp", "sr");
		languages.put("ssw", "ss");
		languages.put("sun", "su");
		languages.put("swa", "sw");
		languages.put("swe", "sv");
		languages.put("tah", "ty");
		languages.put("tam", "ta");
		languages.put("tat", "tt");
		languages.put("tel", "te");
		languages.put("tgk", "tg");
		languages.put("tgl", "tl");
		languages.put("tha", "th");
		languages.put("tib", "bo");
		languages.put("tir", "ti");
		languages.put("ton", "to");
		languages.put("tsn", "tn");
		languages.put("tso", "ts");
		languages.put("tuk", "tk");
		languages.put("tur", "tr");
		languages.put("twi", "tw");
		languages.put("uig", "ug");
		languages.put("ukr", "uk");
		languages.put("urd", "ur");
		languages.put("uzb", "uz");
		languages.put("ven", "ve");
		languages.put("vie", "vi");
		languages.put("vol", "vo");
		languages.put("wel", "cy");
		languages.put("wln", "wa");
		languages.put("wol", "wo");
		languages.put("xho", "xh");
		languages.put("yid", "yi");
		languages.put("yor", "yo");
		languages.put("zha", "za");
		languages.put("româna", "ro");		
		languages.put("netherlands","nl");
		languages.put("mul","en");
		languages.put("sh","hr");
		languages.put("mo", "ro");		
		languages.put("def", "en");		
		languages.put("mul", "en");
		languages.put("scc", "sr");	

	}

	public Map<String, String> getLanguages() {
		return languages;
	}

	public void setLanguages(Map<String, String> languages) {
		this.languages = languages;
	}
	
}
